# Generated by Django 4.2.3 on 2024-08-17 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='question_no',
        ),
    ]
