# Generated by Django 4.2.3 on 2024-08-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_faq_question_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='activity',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
    ]
